language: python
python:
  - "2.7"

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - redis-server redis.conf

install:
  - python setup.py install

script:
  - nosetests --with-timer --ws-url=test_resources/data --wsfile-msgpack --exclude-dir-file=exclude-tests.txt
  - nosetests --with-timer --ws-url=https://ci.kbase.us/services/ws/ --exclude-dir-file=exclude-tests.txt
  - coverage run nosetests --with-timer --ws-url=https://ci.kbase.us/services/ws/ --exclude-dir-file=exclude-tests.txt
  - coverage report

env:
  - KB_REDIS_HOST=localhost
  - KB_REDIS_HOST=

after_success:
  - codecov
