language: python
python:
  - "2.7"

sudo: required

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/thrift

before_install:
  - redis-server redis.conf &
  - export THRIFT_CACHED=0
  - if [ -d '$HOME/thrift/thrift-0.9.2' ]; then export THRIFT_CACHED=1; fi
  - ./install_travis.sh

install:
  - pip install .
  - echo "lib/doekbase/data_api/interactive" > exclude-tests.txt

script:
  - coverage run `which nosetests` -c nose.cfg -c $KB_NOSE_CFG
  - coverage report
  - coverage xml

env:
  - KB_REDIS_HOST=localhost; KB_NOSE_CFG=nose-local.cfg
  - KB_REDIS_HOST="";        KB_NOSE_CFG=nose-local.cfg
#  - KB_REDIS_HOST=localhost; KB_NOSE_CFG=nose-ci.cfg
#  - KB_REDIS_HOST="";        KB_NOSE_CFG=nose-ci.cfg

after_success:
  - codecov
