language: python
python:
  - "2.7"

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - redis-server redis.conf &
  - sudo apt-get update -qq
  - sudo apt-get install libboost-dev libboost-test-dev libboost-program-options-dev libevent-dev automake libtool flex bison pkg-config g++ libssl-dev
  - wget http://www.us.apache.org/dist/thrift/0.9.2/thrift-0.9.2.tar.gz
  - tar xfz thrift-0.9.2.tar.gz
  - cd thrift-0.9.2 && ./configure && sudo make install

install:
  - python setup.py install

script:
  - coverage run `which nosetests` -c nose.cfg -c $KB_NOSE_CFG
  - coverage report

env:
  - KB_REDIS_HOST=localhost; KB_NOSE_CFG=nose-local.cfg
  - KB_REDIS_HOST="";        KB_NOSE_CFG=nose-local.cfg
#  - KB_REDIS_HOST=localhost; KB_NOSE_CFG=nose-ci.cfg
#  - KB_REDIS_HOST="";        KB_NOSE_CFG=nose-ci.cfg

after_success:
  - codecov
