language: python
python:
  - "2.7"

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - redis-server redis.conf &

install:
  - pip install -r requirements.txt
  - python setup.py install -vv

before_script:
  - printf "Build dir = $TRAVIS_BUILD_DIR\n"
  - nohup data_api_start_service.py --service taxon --config deployment.cfg > taxonAPI.out &
  - nohup data_api_start_service.py --service assembly --config deployment.cfg > assemblyAPI.out &
  - nohup data_api_start_service.py --service genome_annotation --config deployment.cfg > genome_annotationAPI.out &

script:
  - coverage run `which nosetests` -c nose.cfg -c nose-local.cfg
  - coverage report --skip-covered

env:
  - KB_DEPLOY_URL="dir_cache"
  - KB_DEPLOY_URL="dir_nocache"
#  - KB_REDIS_HOST=localhost; KB_NOSE_CFG=nose-ci.cfg
#  - KB_REDIS_HOST="";        KB_NOSE_CFG=nose-ci.cfg

after_success:
  - codecov
  - kill $(cat taxonAPI.pid)
  - kill $(cat assemblyAPI.pid)
  - kill $(cat genome_annotationAPI.pid)

after_failure:
  - cat taxonAPI.out
  - cat assemblyAPI.out
  - cat genome_annotationAPI.out
