language: python
python:
  - "2.7"

git:
  submodules: false

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - git submodule update --init --recursive

install:
  - python setup.py install

script:
  - coverage run $HOME/virtualenv/python2.7.9/bin/nosetests --with-timer --ws-url=test_resources/data --wsfile-msgpack
  - coverage report
  - ./run_tests.sh -T

after_success:
  - codecov
